name: blocconote
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  path_provider: ^2.0.2
  flutter_simple_dependency_injection: ^2.0.0
  flutter_launcher_icons: ^0.9.3
  provider: ^6.0.3
  reorderable_grid_view: ^2.2.2
  flutter_reorderable_grid_view: ^3.1.1
  flutter_neumorphic: ^3.2.0
  sqflite: ^2.0.0+3


  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/RobotoMono-Regular.ttf